In [17]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from pydataset import data
from scipy import stats

# Chi$^2$ ($\chi^2$) Test for Independence

aka Pearson's Chi$^2$ test. Pronounced as 'Ki' as in kite.

- Lets us test the hypothesis that one group is independent of another
- $H_0$ is always that there is independence between the groups
- $H_0$ is that there is no dependence


The null hypothesis assumes that the observed frequencies for a categorical variable match the expected frequencies for the categorical variable

## The Quick Way To Run a Chi$^2$ Test

In [18]:
# get data from pydataset
df = data('tips')

In [19]:
df.head()

total_bill   tip     sex smoker  day    time  size
1       16.99  1.01  Female     No  Sun  Dinner     2
2       10.34  1.66    Male     No  Sun  Dinner     3
3       21.01  3.50    Male     No  Sun  Dinner     3
4       23.68  3.31    Male     No  Sun  Dinner     2
5       24.59  3.61  Female     No  Sun  Dinner     4

- $H_0$ There is independence between the smoker and time of the
day
- $H_a$ is that there is a dependence

In [22]:
# pandas crosstab to make a 'contingency' table
observed = pd.crosstab(df.time, df.smoker, margins = True, normalize = 'columns')
observed

smoker        No       Yes       All
time                                
Dinner  0.701987  0.752688  0.721311
Lunch   0.298013  0.247312  0.278689

In [30]:
observed = pd.crosstab(df.time, df.smoker)
observed

smoker   No  Yes
time            
Dinner  106   70
Lunch    45   23

In [31]:
# Set our alpha
alpha = .01

In [32]:
# chi2_contingency returns 4 different values
chi2, p, degf, expected = stats.chi2_contingency(observed)
chi2, p, degf, expected

(0.5053733928754355,
 0.4771485672079724,
 1,
 array([[108.91803279,  67.08196721],
        [ 42.08196721,  25.91803279]]))

In [34]:
if p < alpha:
    print('We reject the null hypo')
else:
    print('We fail to reject the null hypo')

We fail to reject the null hypo


## Attrition Data

In [35]:
# get your data
df = pd.read_csv("https://gist.githubusercontent.com/ryanorsinger/6ba2dd985c9aa92f5598fc0f7c359f6a/raw/b20a508cee46e6ac69eb1e228b167d6f42d665d8/attrition.csv")

In [36]:
df.head(3)

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  

[3 rows x 35 columns]

In [37]:
# check shape of the dataframe
df.shape

(1470, 35)

In [38]:
# Check for which columns are discrete
df.nunique()

Age                           43
Attrition                      2
BusinessTravel                 3
DailyRate                    886
Department                     3
DistanceFromHome              29
Education                      5
EducationField                 6
EmployeeCount                  1
EmployeeNumber              1470
EnvironmentSatisfaction        4
Gender                         2
HourlyRate                    71
JobInvolvement                 4
JobLevel                       5
JobRole                        9
JobSatisfaction                4
MaritalStatus                  3
MonthlyIncome               1349
MonthlyRate                 1427
NumCompaniesWorked            10
Over18                         1
OverTime                       2
PercentSalaryHike             15
PerformanceRating              2
RelationshipSatisfaction       4
StandardHours                  1
StockOptionLevel               4
TotalWorkingYears             40
TrainingTimesLastYear          7
WorkLifeBa

In [ ]:
# Question we want to answer:

# 1. Is Attrition independent from Business Travel amount?
# 2. Is Attrition independent from Department?
# 3. Is Attrition indpendent from WorkLife balance

In [39]:
df.BusinessTravel.value_counts()

Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: BusinessTravel, dtype: int64

Form hypothesis:

$H_0$: Attrition and Travel Frequency are independent (not dependent)

$H_a$: Attrition and Travel Frequency are dependent

In [40]:
# cross tab Attrition vs Business Travel
observed = pd.crosstab(df.Attrition, df.BusinessTravel)

In [41]:
observed

BusinessTravel  Non-Travel  Travel_Frequently  Travel_Rarely
Attrition                                                   
No                     138                208            887
Yes                     12                 69            156

In [42]:
# Set our alpha
alpha = .01

In [44]:
# .chi2_contingency returns 4 different values
chi2, p, degf, expected = stats.chi2_contingency(observed)

In [45]:
chi2, p, degf

(24.182413685655174, 5.608614476449931e-06, 2)

In [46]:
expected 

array([[125.81632653, 232.34081633, 874.84285714],
       [ 24.18367347,  44.65918367, 168.15714286]])

In [47]:
null_hypothesis = "Attrition and Business Travel are independent"

if p < alpha:
    print("We reject the null hypothesis")
    print("We reject the hypothesis that", null_hypothesis)
else:
    print("We fail to reject the null hypothesis")

print(p)

We reject the null hypothesis
We reject the hypothesis that Attrition and Business Travel are independent
5.608614476449931e-06


In [49]:
#Normalized crosstab
observed = pd.crosstab(df.Attrition, df.BusinessTravel, normalize = True)
observed

BusinessTravel  Non-Travel  Travel_Frequently  Travel_Rarely
Attrition                                                   
No                0.093878           0.141497       0.603401
Yes               0.008163           0.046939       0.106122

In [53]:
# make a heatmap
plt.heat(observed)

AttributeError: module 'matplotlib.pyplot' has no attribute 'heat'

## Let's Test for Independence of Attrition and Deparment
- $H_0$: There is no relationship between them, Attrition and Deparment are independent
- $H_a$: There is a relationship

In [ ]:
#crosstab for observed values between Attrition and Depts


In [54]:
# Let's get the p value from a chi2 test for independence
chi2, p, degf, expected = stats.chi2_contingency(observed)
chi2, p, degf, expected

(0.01645062155486746,
 0.9918084245334221,
 2,
 array([[0.08558934, 0.15805498, 0.5951312 ],
        [0.01645148, 0.0303804 , 0.11439261]]))

In [55]:
if p < alpha:
    print("We reject the null")
else:
    print("We fail to reject the null")



We fail to reject the null


In [ ]:
# Is attrition and being in sales related?

In [56]:
df["in_sales"] = df.Department == "Sales"

In [57]:
df.head(2)

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   

   ...  StandardHours StockOptionLevel  TotalWorkingYears  \
0  ...             80                0                  8   
1  ...             80                1                 10   

   TrainingTimesLastYear  WorkLifeBalance YearsAtCompany  YearsInCurrentRole  \
0                      0                1              6                   4   
1                      3                3             10                   7   

  YearsSinceLastPromotion  YearsWithCurrManager  in_sales  
0                       0                     5      True  
1                       1                     7     False  

[2 rows x 36 columns]

In [59]:
# crosstab between Attrition and in_sales column
observed = pd.crosstab(df.Attrition, df.in_sales)
observed

in_sales   False  True 
Attrition              
No           879    354
Yes          145     92

#### $H_0$: Attrition and Being in Sales or Not are independent
#### $H_a$: There is a relationship

In [60]:
chi2, p, degf, expected = stats.chi2_contingency(observed)

if p < alpha:
    print("We reject the null")
else:
    print("We fail to reject the null")

p

We reject the null


0.0025036788527795267

## Let's test for independence between WorkLifeBalance and Attrition
- $H_0$: WorkLifeBalance and Attrition are independent, no relationship
- $H_a$: They are dependent - there is a relationship

WorkLifeBalance   
1 'Bad'  
2 'Good'  
3 'Better'  
4 'Best'  

In [63]:
#look at value counts
df.WorkLifeBalance.value_counts()

3    893
2    344
4    153
1     80
Name: WorkLifeBalance, dtype: int64

In [64]:
# Crosstab for Attrition and WorklifeBalance
observed = pd.crosstab(df.Attrition, df.WorkLifeBalance)

In [65]:
chi2, p, degf, expected = stats.chi2_contingency(observed)

if p < alpha:
    print("We reject the null hypothesis")
else:
    print("We fail to reject the null")

We reject the null hypothesis


In [68]:
p # There is a relationship between worklife balance and attrition

0.0009725698845348824

In [70]:
# Now, let's control for Department

In [ ]:
# df.Department.value_counts()

In [99]:
# make new dataframes for each dept
r_n_d = df[df.Department == 'Research & Development']
sales = df[df.Department == 'Sales']
hr = df[df.Department == "hr"]

In [100]:
# Run the chi squared test for independence on only RND
observed = pd.crosstab(r_n_d.Attrition, r_n_d.WorkLifeBalance)
observed 

WorkLifeBalance   1    2    3   4
Attrition                        
No               41  203  507  77
Yes              19   32   68  14

In [101]:
chi2, p, degf, expected = stats.chi2_contingency(observed)

if p < alpha:
    print("We reject the null hypothesis")
else:
    print("We fail to reject the null")
p

We reject the null hypothesis


0.0004119601633396577

In [102]:
# how about for sales?
observed = pd.crosstab(sales.Attrition, sales.WorkLifeBalance)
observed 

WorkLifeBalance   1   2    3   4
Attrition                       
No               10  78  226  40
Yes               6  24   50  12

In [103]:
chi2, p, degf, expected = stats.chi2_contingency(observed)

if p < alpha:
    print("We reject the null hypothesis")
else:
    print("We fail to reject the null")
p

We fail to reject the null


0.20695513054029363

In [104]:
# How about for HR?
observed = pd.crosstab(hr.Attrition, hr.WorkLifeBalance)
observed 

Empty DataFrame
Columns: []
Index: []

In [105]:
chi2, p, degf, expected = stats.chi2_contingency(observed)

if p < alpha:
    print("We reject the null hypothesis")
else:
    print("We fail to reject the null")
p

ValueError: No data; `observed` has size 0.

## Findings So Far:
$H_0$ is that there is no relationship. Worklife and Attrition are indpendent

- Research and Development, we reject the null hypothesis
- Sales, we fail to reject the null. This could be due to small population size.
- HR, we fail to reject the null. This could be due to small population size

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [106]:
# Exercises 

In [ ]:
#1) Use the following contingency table to help answer the question of whether using a macbook 
# and being a codeup student are independent of each other.

In [133]:
conf_interval = 0.95
alpha =1 - conf_interval

In [136]:
contengency = pd.DataFrame({'codeup_student': [49,1], 'not_codeup': [20,30]}, index=['uses_mac', 'no_mac'])
contengency

codeup_student  not_codeup
uses_mac              49          20
no_mac                 1          30

In [140]:
chi2, p, degf, expected = stats.chi2_contingency(contengency)

if p < alpha:
    print("We reject the null hypothesis")
else:
    print("We fail to reject the null")

chi2, p, degf, expected

We reject the null hypothesis


(36.65264142122487,
 1.4116760526193828e-09,
 1,
 array([[34.5, 34.5],
        [15.5, 15.5]]))

In [ ]:
#2) Choose another 2 categorical variables from the mpg dataset and perform a chi2 contingency 
# table test with them. Be sure to state your null and alternative hypotheses.

In [142]:
df = data('mpg')
df.info

<bound method DataFrame.info of     manufacturer   model  displ  year  cyl       trans drv  cty  hwy fl  \
1           audi      a4    1.8  1999    4    auto(l5)   f   18   29  p   
2           audi      a4    1.8  1999    4  manual(m5)   f   21   29  p   
3           audi      a4    2.0  2008    4  manual(m6)   f   20   31  p   
4           audi      a4    2.0  2008    4    auto(av)   f   21   30  p   
5           audi      a4    2.8  1999    6    auto(l5)   f   16   26  p   
..           ...     ...    ...   ...  ...         ...  ..  ...  ... ..   
230   volkswagen  passat    2.0  2008    4    auto(s6)   f   19   28  p   
231   volkswagen  passat    2.0  2008    4  manual(m6)   f   21   29  p   
232   volkswagen  passat    2.8  1999    6    auto(l5)   f   16   26  p   
233   volkswagen  passat    2.8  1999    6  manual(m5)   f   18   26  p   
234   volkswagen  passat    3.6  2008    6    auto(s6)   f   17   26  p   

       class  
1    compact  
2    compact  
3    compact  
4    co

In [145]:
a = df.manufacturer
b = df.drv

In [146]:
b.value_counts()

f    106
4    103
r     25
Name: drv, dtype: int64

In [148]:
null = 'manufacuturer is independent of the drivetrain of type on vehicals'
observed = pd.crosstab(a,b)
observed

drv            4   f   r
manufacturer            
audi          11   7   0
chevrolet      4   5  10
dodge         26  11   0
ford          13   0  12
honda          0   9   0
hyundai        0  14   0
jeep           8   0   0
land rover     4   0   0
lincoln        0   0   3
mercury        4   0   0
nissan         4   9   0
pontiac        0   5   0
subaru        14   0   0
toyota        15  19   0
volkswagen     0  27   0

In [150]:
chi2, p, degf, expected = stats.chi2_contingency(observed)

if p < alpha:
    print("We reject the null hypothesis")
else:
    print("We fail to reject the null")

chi2, p, degf, expected

We reject the null hypothesis


(232.03448840753833,
 5.12809407673465e-34,
 28,
 array([[ 7.92307692,  8.15384615,  1.92307692],
        [ 8.36324786,  8.60683761,  2.02991453],
        [16.28632479, 16.76068376,  3.95299145],
        [11.0042735 , 11.32478632,  2.67094017],
        [ 3.96153846,  4.07692308,  0.96153846],
        [ 6.16239316,  6.34188034,  1.4957265 ],
        [ 3.52136752,  3.62393162,  0.85470085],
        [ 1.76068376,  1.81196581,  0.42735043],
        [ 1.32051282,  1.35897436,  0.32051282],
        [ 1.76068376,  1.81196581,  0.42735043],
        [ 5.72222222,  5.88888889,  1.38888889],
        [ 2.2008547 ,  2.26495726,  0.53418803],
        [ 6.16239316,  6.34188034,  1.4957265 ],
        [14.96581197, 15.4017094 ,  3.63247863],
        [11.88461538, 12.23076923,  2.88461538]]))

In [213]:
#3) Use the data from the employees database to answer these questions:
from env import host, password, user

# Function to connect to database.

def get_connection(db, user=user, host=host, password=password):
    return f'mysql+pymysql://{user}:{password}@{host}/{db}'

# Create SQL query to acquire desired data.

sql_query = '''
            SELECT 
                e.gender,
                d.dept_name
            FROM employees AS e
            JOIN dept_emp AS de ON e.emp_no = de.emp_no
                AND to_date > CURDATE()
            JOIN departments AS d USING(dept_no)
            '''

# Read data from database using sql and assign DataFrame to df.

df = pd.read_sql(sql_query, get_connection('employees'))
df

gender         dept_name
0           M  Customer Service
1           F  Customer Service
2           M  Customer Service
3           F  Customer Service
4           F  Customer Service
...       ...               ...
240119      F             Sales
240120      M             Sales
240121      M             Sales
240122      F             Sales
240123      F             Sales

[240124 rows x 2 columns]

In [159]:
#a) Is an employee's gender independent of whether an employee works in sales or marketing? (only look at current employees)
df = df[(df.dept_name == 'Sales')|(df.dept_name == "Marketing")]
df

gender  dept_name
104290      F  Marketing
104291      M  Marketing
104292      F  Marketing
104293      F  Marketing
104294      F  Marketing
...       ...        ...
240119      F      Sales
240120      M      Sales
240121      M      Sales
240122      F      Sales
240123      F      Sales

[52543 rows x 2 columns]

In [166]:
observed = pd.crosstab(df.gender, df.dept_name)
observed

dept_name  Marketing  Sales
gender                     
F               5864  14999
M               8978  22702

In [167]:
chi2, p, degf, expected = stats.chi2_contingency(observed)

if p < alpha:
    print("We reject the null hypothesis")
else:
    print("We fail to reject the null")

chi2, p, degf, expected # not enough infor to reject null

We fail to reject the null


(0.3240332004060638,
 0.5691938610810126,
 1,
 array([[ 5893.2426013, 14969.7573987],
        [ 8948.7573987, 22731.2426013]]))

In [215]:
#b) Is an employee's gender independent of whether or not they are or have been a manager?
query = '''Select e.emp_no, e.gender
From employees as e
Left Join dept_manager as dm on e.emp_no = dm.emp_no'''

In [203]:
gender_manager = pd.read_sql(query, get_connection('employees'))


In [216]:
observed = pd.crosstab(gender, dept_no)
observed

NameError: name 'gender' is not defined