In [36]:

from pydataset import data
from math import sqrt
import pandas as pd
import numpy as np
import scipy.stats
np.random.seed(1349)

In [42]:
#1) How likely is it that you roll doubles when rolling two dice?
first_die = np.random.choice([1,2,3,4,5,6], size = 1_000_000)
secound_die = np.random.choice([1,2,3,4,5,6], size = 1_000_000)
first_die, secound_die


(array([1, 3, 2, ..., 6, 6, 4]), array([1, 2, 4, ..., 5, 5, 5]))

In [43]:
first_die == secound_die

array([ True, False, False, ..., False, False, False])

In [46]:
(first_die == secound_die).mean() # Probability of rolling doubles with two die = .16695

0.166443

In [59]:
#2) If you flip 8 coins, what is the probability of getting exactly 3 heads? 
n_simulations = 1_000_000
n_trials = 8
heads = 1
tails = 0
flips = np.random.choice([heads, tails], size =(n_simulations, n_trials))
flips

sum_of_flips = flips.sum(axis=1)
(sum_of_flips == 3).mean()

0.218966

In [64]:
#A) What is the probability of getting more than 3 heads?
(sum_of_flips >= 3).mean() 

0.855593

In [71]:
#3) There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, 
# what are the odds that the two billboards I drive past both have data science students on them?
sim = 1_000_000
trials = 2
data = 1
web = 0
commutes = np.random.choice ([data, web], size=(sim, trials), p=[0.25, 0.75]) 
# 1/4 proablity to see a data billboard
prob = (commutes.sum(axis=1) == 2).mean()
# checks if both are data 1+1 
prob

0.062336

In [76]:
Theoretical = (1/4) * (1/4)
Theoretical

0.0625

In [99]:
#4) Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. 
# If on monday the machine is restocked with 17 poptart packages, 
# how likely is it that I will be able to buy some poptarts on Friday afternoon?
avg_pop = 3 
pop_std = 1.5
sim = 1_000_000
trials = 5
simulation = np.random.normal(avg_pop, pop_std, size=(sim, trials)) 
simulation

array([[2.88729331, 4.86938208, 3.31869837, 5.41707691, 1.12987762],
       [3.29106153, 2.78374806, 0.68620314, 2.53444722, 2.71206111],
       [4.91300579, 1.55279486, 2.72546567, 2.2506544 , 0.18974813],
       ...,
       [3.42686683, 2.41180536, 3.95129704, 0.72946599, 0.35350001],
       [5.93073367, 2.92459748, 3.9518339 , 2.2075249 , 4.54062255],
       [2.11073589, 2.6591559 , 3.07081125, 1.99630841, 2.80606817]])

In [101]:
probablity= (simulation.sum(axis=1) < 17).mean()
probablity

0.724136

In [112]:
#5) Compare Heights

    #Men have an average height of 178 cm and standard deviation of 8cm.
    #Women have a mean of 170, sd = 6cm.
    #If a man and woman are chosen at random, P(woman taller than man)?

In [110]:
men = 178
mstd = 8
women = 170
wstd = 6

s_men = np.random.normal(men, mstd, 1_000_000)
s_men

s_women = np.random.normal(women, wstd, 1_000_000)
s_women

calculated_prob = (s_women > s_men).mean()
calculated_prob

0.211511

In [117]:
#6) When installing anaconda on a student's computer, there's a 1 in 250 #
#chance that the download is corrupted and the installation fails. 
#What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

# 99.6 % percent will not have issues
sim = 1_000_000
trials = 50 # number of students
fail = 1
success = 0
#1/250 = 0.004 prob
simulation = np.random.choice([fail, success], size = (sim, trials), p=[0.004, 0.996])

prob= (simulation.sum(axis=1) > 0 ).mean()
prob

0.18189

In [119]:
#A) What is the probability that we observe an installation issue within the first 150 students that download anaconda?
sim = 1_000_000
trials = 150 # number of students
fail = 1
success = 0
#1/250 = 0.004 prob
simulation = np.random.choice([fail, success], size = (sim, trials), p=[0.004, 0.996])

prob= (simulation.sum(axis=1) > 0 ).mean()
prob

0.451982

In [123]:
#B) How likely is it that 450 students all download anaconda without an issue?
sim = 1_000_000
trials = 450 # number of students
fail = 1
success = 0
#1/250 = 0.004 prob
simulation = np.random.choice([fail, success], size = (sim, trials), p=[0.004, 0.996])

prob= (simulation.sum(axis=1) > 0 ).mean()
prob

0.835913

In [121]:
#C)
sim = 1_000_000
trials = 100 # number of students
fail = 1
success = 0
#1/250 = 0.004 prob
simulation = np.random.choice([fail, success], size = (sim, trials), p=[0.004, 0.996])

prob= (simulation.sum(axis=1) > 0 ).mean()
prob

0.330059

In [127]:
#7) There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
# However, you haven't seen a food truck there in 3 days. How unlikely is this?
sim = 1_000_000
trials = 5
ft = 1
noft = 0

simulation = np.random.choice([ft, noft], size = (sim, trials), p = [0.70, 0.30]) 

prob = (simulation.sum(axis = 1) == 0).mean()
prob # how unlikely it is to have three days no ft

0.002491

In [128]:
#A) How likely is it that a food truck will show up sometime this week?
sim = 1_000_000
trials = 3
ft = 1
noft = 0
simulation = np.random.choice([ft, noft], size = (sim, trials), p = [0.70, 0.30])
prob = (simulation.sum(axis = 1) == 0).mean()
prob

0.026615

In [ ]:
#8) If 23 people are in the same room, what are the odds that two of them share a birthday? 
outcomes = range(0, 365)
n_simulations = 1_000_000 # number of combinations for same birth days(Birthday Paradox)
n_trials = 23
simulation = np.random.choice(outcomes, size =(n_simulations, n_trials))
len(simulation[0])
combo_bday = [len(np.unique(simulation[n])) for n in range(0, n_simulations-1) if len(np.unique(simulation[n])) < 23]
combo_bday.mean()

In [ ]:
# What if it's 20 people? 
outcomes = range(0, 365)
n_simulations = 1_000_000 # number of combinations 
n_trials = 20
simulation = np.random.choice(outcomes, size =(n_simulations, n_trials))
combo_bday = [len(np.unique(simulation[n])) for n in range(0, n_simulations-1) if len(np.unique(simulation[n])) < 20]
simulation/len(combo_bday)

In [151]:
# 40?
outcomes = range(0, 365)
n_simulations = 1_000_000 # number of combinations 
n_trials = 40
simulation = np.random.choice(outcomes, size =(n_simulations, n_trials))
combo_bday.mean()
combo_bday = [len(np.unique(simulation[n])) for n in range(0, n_simulations-1) if len(np.unique(simulation[n])) < 40]
combo_bday.mean()

AttributeError: 'list' object has no attribute 'mean'